### ISSUE TITLE
19142368: Crash while calling class initializer via generic method in Swift

### ISSUE THREAD

**Issue by openradar-mirror** [lionheart/openradar-mirror#2547]
#### Description

Summary:
App crashes when trying to create class via convenience initializer.
Requirements :
• Use Swift
• initializer should be described in protocol
• convenience initializer described in protocol should be implemented in class extension
• initializer should be called with a help of generic method
• class should be marked with @objc

Crash happens with Xcode 6.1.1 (6A2008a) and Xcode 6.2 (6C86e). But perfectly works with Xcode 6.1 (6A1052d)

Example:

protocol P {
    init(name: String)
}

@objc
final class C {
    var name = "John Doe";

```
required init() {
}
```

}

extension C: P {
    convenience init(name: String) {
        self.init()
        self.name = name;
    }
}

func create<T: P>(name: String) -> T {
    return T(name: name)
}

create("Bob") as C // Crash !!!

Steps to Reproduce:
1. Implement protocol:
protocol P {
    init(name: String)
}
1. Implement class:
   @objc
   final class C {
   var name = "John Doe";
   
   required init() {
   }
   }

extension C: P {
    convenience init(name: String) {
        self.init()
        self.name = name;
    }
}

3.Implement generic method:
func create<T: P>(name: String) -> T {
    return T(name: name)
}
4. call method described on step [3]:
let person = create("Bob") as C

Expected Results:
person variable should contain class C with name Bob

Actual Results:
Crash:
NSForwarding: warning: object 0x10c699c20 of class 'MyApp.C' does not implement methodSignatureForSelector: -- trouble ahead
Unrecognized selector +[MyApp.C initWithName:]

Version:
OS X 10.10.2 (14C68m)
Xcode 6.1.1 (6A2008a)
Xcode 6.2 (6C86e)

Notes:
Tested in iOS app with 8.x simulator.

Workarounds:
1. Use Xcode 6.1 (6A1052d)
1. Don't implement convenience initializer in class extension:

@objc
final class C: P {
    var name = "John Doe";

```
required init() {
}

convenience init(name: String) {
    self.init()
    self.name = name;
}
```

}
1. Use class factory method instead:

protocol P {
    class func create(name: String) -> Self
}

@objc
final class C {
    var name = "John Doe";

```
required init() {
}
```

}

extension C: P {

```
class func create(name: String) -> C {
    let c = C()
    c.name = name
    return c
}
```

}

func create<T: P>(name: String) -> T {
    return T.create(name)
}
1. Don't use @objc mark, if you don't want objective-c support for your class
## 

Product Version: 
Created: 2014-12-04T14:13:23.337841
Originated: 2014-12-04T00:00:00
Open Radar Link: http://www.openradar.me/19142368
