### ISSUE TITLE
25442928: Swift Mac Command Line Tool target cannot link with -ObjC flag in Xcode 7.3

### ISSUE THREAD

**Issue by openradar-mirror** [lionheart/openradar-mirror#7882]
#### Description

Description:
When linking, many duplicate symbol errors are thrown from the linker for ErrorObject and SwiftObject in libswiftRuntime.a and libswiftCore.a. This does not occur in Xcode 7.2.1

Repro steps:
1. Create new Xcode 7.3 project for a mac command line tool
2. Build and run to confirm everything works
3. Add -ObjC to OTHER_LDFLAGS
4. Try to build again
5. Try to build now in Xcode 7.2.1

Expected results: 
Project should build fine in both Xcode 7.2.1 and 7.3

Actual results:
LD fails due to the mentioned duplicate symbol errors in Xcode 7.3, but not in Xcode 7.2.1

Setup:
Version 7.3 (7D175), OS X 10.11.4 (15E65)

Sample project available at https://www.dropbox.com/s/0xqt4j1kzdzen6b/swift_cli_xcode7_3.zip?dl=0
## 

Product Version: 7.3 (7D175)
Created: 2016-03-30T17:32:02.716430
Originated: 2016-03-30T00:00:00
Open Radar Link: http://www.openradar.me/25442928
