### ISSUE TITLE
30194818: Xcode 8.3 beta 1 (8W109m): "Redefinition of module 'ModuleName'" build error

### ISSUE THREAD

**Issue by openradar-mirror** [lionheart/openradar-mirror#16793]
#### Description

Summary:
Building an Objective-C project with C, C++, ObjC, ObjC++ sources with a custom module map that previously compiled successfully with Xcode 7.0-8.2.1 fails to compile with Xcode 8.3 beta 1 (8W109m).

Steps to Reproduce:
1. git clone https://github.com/realm/realm-cocoa.git
2. cd realm-cocoa
3. git submodule update --init --recursive
4. git checkout v2.3.0 # optional
5. open -a Xcode-8.3.app .
6. Select the "Realm" scheme with "My Mac" as a build target
7. CMD-B to build

Expected Results:
Should compile successfully.

Actual Results:
Fails to compile with the following error:

```
/path/to/project/realm-cocoa/Realm/module.modulemap:1:18: error: redefinition of module 'Realm'
framework module Realm {
                 ^
/Users/me/Library/Developer/Xcode/DerivedData/Realm-fgnurdgvwrgrprepohogrgawtdgm/Build/Intermediates/Realm.build/Debug/Realm.build/module.modulemap:1:18: note: previously defined here
framework module Realm {
                 ^
1 error generated.
```

Regression:
Removing the custom module map from the build settings makes the target compile successfully, but that's not an option for us, since we make use of clang submodules.
Replacing the contents of the custom module map with the contents of the default Xcode-generated modulemap that's produced when removing the custom module map build setting still produces the same error.

Notes:
Provide additional information, such as references to related problems, workarounds and relevant attachments.

-
Product Version: Xcode-8.3 (8W109m)
Created: 2017-01-25T22:12:56.647220
Originated: 2017-01-25T14:12:00
Open Radar Link: http://www.openradar.me/30194818

**Comment by liufsd** [comment]
Version 8.3.1 (8E1000a)
+1

**Comment by openradar-mirror** [comment]
Resolved: 20-Apr-2017 02:12 PM
Modified: 2017-04-20T19:42:17.245630
